=== KoenM-bit/opentrons/shared-data/deck/schemas/4.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "positiveNumber": {
      "type": "number",
      "minimum": 0
    },
    "xyzArray": {
      "type": "array",
      "description": "Array of 3 numbers, [x, y, z]",
      "items": { "type": "number" },
      "minItems": 3,
      "maxItems": 3
    },
    "coordinates": {
      "type": "object",
      "additionalProperties": false,
      "required": ["x", "y", "z"],
      "properties": {
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        },
        "z": {
          "type": "number"
        }
      }
    },
    "unitVector": {
      "type": "array",
      "description": "Array of 3 unit directions, [x, y, z]",
      "items": {
        "type": "number",
        "enum": [1, -1]
      },
      "minItems": 3,
      "maxItems": 3
    },
    "boundingBox": {
      "type": "object",
      "description": "The active area (both pipettes can reach) of a fixture on the deck",
      "required": ["xDimension", "yDimension", "zDimension"],
      "properties": {
        "xDimension": { "$ref": "#/definitions/positiveNumber" },
        "yDimension": { "$ref": "#/definitions/positiveNumber" },
        "zDimension": { "$ref": "#/definitions/positiveNumber" }
      }
    },
    "svgsonNode": {
      "type": "object",
      "description": "An svgson node that corresponds to a single svg tag",
      "properties": {
        "name": {
          "type": "string",
          "description": "Element name, like svg, circle, line…"
        },
        "type": {
          "type": "string",
          "description": "Element type like element, text…"
        },
        "value": {
          "type": "string",
          "description": "Element value, used in text nodes."
        },
        "children": {
          "type": "array",
          "description": "List of element children",
          "items": { "$ref": "#/definitions/svgsonNode" }
        },
        "attributes": {
          "type": "object",
          "description": "Attributes for the element"
        }
      }
    },
    "cutoutSlot": {
      "type": "string",
      "enum": [
        "A1",
        "A2",
        "A3",
        "B1",
        "B2",
        "B3",
        "C1",
        "C2",
        "C3",
        "D1",
        "D2",
        "D3"
      ]
    }
  },
  "description": "Deck specifications, where x,y,z (0,0,0) is at front the bottom left corner.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "otId",
    "schemaVersion",
    "cornerOffsetFromOrigin",
    "dimensions",
    "metadata",
    "robot",
    "locations",
    "cutoutFixtures",
    "layers"
  ],
  "properties": {
    "otId": {
      "description": "Unique internal ID generated using UUID",
      "type": "string"
    },
    "schemaVersion": {
      "description": "Schema version of a deck is a single integer",
      "enum": [4]
    },
    "cornerOffsetFromOrigin": {
      "$ref": "#/definitions/xyzArray",
      "description": "Position of left-front-bottom corner of entire deck to robot coordinate system origin"
    },
    "dimensions": {
      "$ref": "#/definitions/xyzArray",
      "description": "Outer dimensions of a deck bounding box"
    },
    "metadata": {
      "description": "Optional metadata about the Deck",
      "type": "object",
      "properties": {
        "displayName": {
          "description": "A short, human-readable name for the deck",
          "type": "string"
        },
        "tags": {
          "description": "Tags to be used in searching for this deck",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "robot": {
      "type": "object",
      "required": ["model"],
      "properties": {
        "model": {
          "description": "Model of the robot",
          "type": "string",
          "enum": ["OT-2 Standard", "OT-3 Standard"]
        }
      }
    },
    "locations": {
      "type": "object",
      "required": ["addressableAreas", "cutouts"],
      "properties": {
        "addressableAreas": {
          "type": "array",
          "description": "Ordered slots available for placing labware",
          "items": {
            "type": "object",
            "required": [
              "id",
              "areaType",
              "position",
              "boundingBox",
              "displayName"
            ],
            "properties": {
              "id": {
                "description": "Unique identifier for slot",
                "type": "string"
              },
              "areaType": {
                "description": "The type of deck item, defining allowed behavior.",
                "type": "string",
                "enum": ["slot", "movableTrash", "wasteChute"]
              },
              "position": {
                "$ref": "#/definitions/xyzArray",
                "description": "Relative position of the addressable area as it sits on the cutout slot."
              },
              "matingSurfaceUnitVector": {
                "$ref": "#/definitions/unitVector",
                "description": "An optional diagonal direction of force, defined by spring location, which governs the mating surface of objects placed in slot."
              },
              "boundingBox": {
                "$ref": "#/definitions/boundingBox"
              },
              "displayName": {
                "description": "A human-readable nickname for this area e.g. \"Slot A1\" or \"Movable Trash\"",
                "type": "string"
              },
              "compatibleModuleTypes": {
                "description": "An array of module types that can be placed in this area.",
                "type": "array",
                "items": {
                  "type": "string",
                  "enum": [
                    "magneticModuleType",
                    "temperatureModuleType",
                    "thermocyclerModuleType",
                    "heaterShakerModuleType",
                    "magneticBlockType"
                  ]
                }
              },
              "ableToDropTips": {
                "description": "Whether tips are allowed to be dropped into this area.",
                "type": "boolean"
              },
              "ableToDropLabware": {
                "description": "Whether labware is allowed to be dropped (different then being placed) into this area.",
                "type": "boolean"
              },
              "dropTipsOffset": {
                "description": "Positional offset of where the pipette should drop tips from.",
                "$ref": "#/definitions/xyzArray"
              },
              "dropLabwareOffset": {
                "description": "Positional offset of where the gripper should drop labware from.",
                "$ref": "#/definitions/xyzArray"
              }
            }
          }
        },
        "calibrationPoints": {
          "type": "array",
          "description": "Key points for deck calibration",
          "items": {
            "type": "object",
            "required": ["id", "position", "displayName"],
            "properties": {
              "id": {
                "description": "Unique identifier for calibration point",
                "type": "string"
              },
              "position": {
                "$ref": "#/definitions/xyzArray"
              },
              "displayName": {
                "description": "An optional human-readable nickname for this point Eg \"Slot 3 Cross\" or \"Slot 1 Dot\"",
                "type": "string"
              }
            }
          }
        },
        "cutouts": {
          "type": "array",
          "description": "The machined cutout slots on the deck surface.",
          "items": {
            "type": "object",
            "required": [
              "id",
              "position",
              "displayName",
              "compatibleFixtureTypes"
            ],
            "properties": {
              "id": {
                "description": "Unique identifier for the cutout",
                "type": "string"
              },
              "position": {
                "description": "Absolute position of the cutout",
                "$ref": "#/definitions/xyzArray"
              },
              "displayName": {
                "description": "An optional human-readable nickname for this cutout e.g. \"Cutout A1\"",
                "type": "string"
              },
              "compatibleFixtureTypes": {
                "description": "Cutout fixtures that can be loaded onto this cutout.",
                "type": "array",
                "items": {
                  "type": "string",
                  "enum": [
                    "singleLeftSlot",
                    "singleCenterSlot",
                    "singleRightSlot",
                    "stagingAreaRightSlot",
                    "trashBinAdapter",
                    "wasteChuteRightAdapter",
                    "wasteChuteRightAdapterWithStagingAreaSlot"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "cutoutFixtures": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "cutoutLocation",
          "fixtureType",
          "displayName",
          "onFixtureItems"
        ],
        "properties": {
          "id": {
            "description": "Unique identifier for the cutout fixture.",
            "type": "string"
          },
          "cutoutLocation": {
            "description": "Cutout locations this cutout fixture can be.",
            "type": "array",
            "items": {
              "$ref": "#/definitions/cutoutSlot"
            }
          },
          "fixtureType": {
            "description": "The type of cutout fixture.",
            "type": "string",
            "enum": [
              "singleLeftSlot",
              "singleCenterSlot",
              "singleRightSlot",
              "stagingAreaRightSlot",
              "trashBinAdapter",
              "wasteChuteRightAdapter",
              "wasteChuteRightAdapterWithStagingAreaSlot"
            ]
          },
          "displayName": {
            "description": "A human-readable nickname for this area e.g. \"Standard Right Slot\" or \"Slot With Movable Trash\"",
            "type": "string"
          },
          "onFixtureItems": {
            "description": "",
            "type": "object",
            "propertyNames": {
              "$ref": "#/definitions/cutoutSlot"
            },
            "additionalProperties": {
              "type": "array",
              "items": {
                "type": "string",
                "enum": [
                  "A1",
                  "A2",
                  "A3",
                  "A4",
                  "B1",
                  "B2",
                  "B3",
                  "B4",
                  "C1",
                  "C2",
                  "C3",
                  "C4",
                  "D1",
                  "D2",
                  "D3",
                  "D4",
                  "movableTrash",
                  "1/8cWasteChute",
                  "96cWasteChute",
                  "gripperWasteChute"
                ]
              }
            }
          }
        }
      }
    },
    "layers": {
      "type": "array",
      "description": "Layered feature groups of the deck.",
      "items": {
        "$ref": "#/definitions/svgsonNode"
      }
    },
    "gripperOffsets": {
      "type": "object",
      "description": "Offsets to be added when calculating the coordinates a gripper should go to when picking up or dropping a labware on this deck.",
      "properties": {
        "default": {
          "type": "object",
          "properties": {
            "pickUpOffset": {
              "$ref": "#/definitions/coordinates",
              "description": "Offset added to calculate pick-up coordinates of a labware placed on this deck."
            },
            "dropOffset": {
              "$ref": "#/definitions/coordinates",
              "description": "Offset added to calculate drop coordinates of a labware placed on this deck."
            }
          },
          "required": ["pickUpOffset", "dropOffset"]
        }
      },
      "required": ["default"]
    }
  }
}

=== KoenM-bit/opentrons/shared-data/deck/definitions/4/ot3_standard.json
{
  "otId": "ot3_standard",
  "schemaVersion": 4,
  "cornerOffsetFromOrigin": [-204.31, -76.59, 0],
  "dimensions": [854.995, 581.74, 0],
  "metadata": {
    "displayName": "OT-3 Standard Deck",
    "tags": ["ot3", "12 slots", "standard"]
  },
  "robot": {
    "model": "OT-3 Standard"
  },
  "locations": {
    "addressableAreas": [
      {
        "id": "D1",
        "areaType": "slot",
        "matingSurfaceUnitVector": [-1, 1, -1],
        "position": [0.0, 0.0, 0.0],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot D1",
        "compatibleModuleTypes": [
          "temperatureModuleType",
          "heaterShakerModuleType",
          "magneticBlockType"
        ]
      },
      {
        "id": "D2",
        "areaType": "slot",
        "matingSurfaceUnitVector": [-1, 1, -1],
        "position": [0.0, 0.0, 0.0],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot D2",
        "compatibleModuleTypes": ["magneticBlockType"]
      },
      {
        "id": "D3",
        "areaType": "slot",
        "position": [0.0, 0.0, 0.0],
        "matingSurfaceUnitVector": [-1, 1, -1],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot D3",
        "compatibleModuleTypes": [
          "temperatureModuleType",
          "heaterShakerModuleType",
          "magneticBlockType"
        ]
      },
      {
        "id": "C1",
        "areaType": "slot",
        "position": [0.0, 0.0, 0.0],
        "matingSurfaceUnitVector": [-1, 1, -1],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot C1",
        "compatibleModuleTypes": [
          "temperatureModuleType",
          "heaterShakerModuleType",
          "magneticBlockType"
        ]
      },
      {
        "id": "C2",
        "areaType": "slot",
        "position": [0.0, 0.0, 0.0],
        "matingSurfaceUnitVector": [-1, 1, -1],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot C2",
        "compatibleModuleTypes": ["magneticBlockType"]
      },
      {
        "id": "C3",
        "areaType": "slot",
        "position": [0.0, 0.0, 0.0],
        "matingSurfaceUnitVector": [-1, 1, -1],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot C3",
        "compatibleModuleTypes": [
          "temperatureModuleType",
          "heaterShakerModuleType",
          "magneticBlockType"
        ]
      },
      {
        "id": "B1",
        "areaType": "slot",
        "position": [0.0, 0, 0.0],
        "matingSurfaceUnitVector": [-1, 1, -1],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot B1",
        "compatibleModuleTypes": [
          "temperatureModuleType",
          "thermocyclerModuleType",
          "heaterShakerModuleType",
          "magneticBlockType"
        ]
      },
      {
        "id": "B2",
        "areaType": "slot",
        "position": [0.0, 0.0, 0.0],
        "matingSurfaceUnitVector": [-1, 1, -1],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot B2",
        "compatibleModuleTypes": ["magneticBlockType"]
      },
      {
        "id": "B3",
        "areaType": "slot",
        "position": [0.0, 0.0, 0.0],
        "matingSurfaceUnitVector": [-1, 1, -1],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot B3",
        "compatibleModuleTypes": [
          "temperatureModuleType",
          "heaterShakerModuleType",
          "magneticBlockType"
        ]
      },
      {
        "id": "A1",
        "areaType": "slot",
        "position": [0.0, 0.0, 0.0],
        "matingSurfaceUnitVector": [-1, 1, -1],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot A1",
        "compatibleModuleTypes": [
          "temperatureModuleType",
          "heaterShakerModuleType",
          "thermocyclerModuleType",
          "magneticBlockType"
        ]
      },
      {
        "id": "A2",
        "areaType": "slot",
        "position": [0.0, 0.0, 0.0],
        "matingSurfaceUnitVector": [-1, 1, -1],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot A2",
        "compatibleModuleTypes": ["magneticBlockType"]
      },
      {
        "id": "A3",
        "areaType": "slot",
        "position": [0.0, 0.0, 0.0],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot A3",
        "compatibleModuleTypes": [
          "temperatureModuleType",
          "heaterShakerModuleType",
          "magneticBlockType"
        ]
      },
      {
        "id": "A4",
        "areaType": "slot",
        "position": [164.0, 0.0, 14.5],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot A4",
        "compatibleModuleTypes": []
      },
      {
        "id": "B4",
        "areaType": "slot",
        "position": [164.0, 0.0, 14.5],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot B4",
        "compatibleModuleTypes": []
      },
      {
        "id": "C4",
        "areaType": "slot",
        "position": [164.0, 0.0, 14.5],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot C4",
        "compatibleModuleTypes": []
      },
      {
        "id": "D4",
        "areaType": "slot",
        "position": [164.0, 0.0, 14.5],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot D4",
        "compatibleModuleTypes": []
      },
      {
        "id": "movableTrash",
        "areaType": "movableTrash",
        "position": [-17.0, -2.75, 0.0],
        "boundingBox": {
          "xDimension": 246.5,
          "yDimension": 91.5,
          "zDimension": 40
        },
        "displayName": "Movable Trash"
      },
      {
        "id": "1/8cWasteChute",
        "areaType": "wasteChute",
        "position": [-13.50, 0, 0],
        "boundingBox": {
          "xDimension": 155.0,
          "yDimension": 86.0,
          "zDimension": 154.0
        },
        "displayName": "1/8 Channel Waste Chute",
        "ableToDropLabware": false,
        "ableToDropTips": true,
        "dropTipsOffset": [64, 21.91, 144.0]
      },
      {
        "id": "96cWasteChute",
        "areaType": "wasteChute",
        "position": [-13.50, 0, 0],
        "boundingBox": {
          "xDimension": 155.0,
          "yDimension": 86.0,
          "zDimension": 154.0
        },
        "displayName": "96 Channel Waste Chute",
        "ableToDropLabware": false,
        "ableToDropTips": true,
        "dropTipsOffset": [14.445, 42.085, 115]
      },
      {
        "id": "gripperWasteChute",
        "areaType": "wasteChute",
        "position": [-13.50, 0, 0],
        "boundingBox": {
          "xDimension": 155.0,
          "yDimension": 86.0,
          "zDimension": 154.0
        },
        "displayName": "Gripper Waste Chute",
        "ableToDropLabware": true,
        "ableToDropTips": false,
        "dropLabwareOffset": [64, 29, 136.5]
      }
    ],
    "cutouts": [
      {
        "id": "D1",
        "position": [0.0, 0.0, 0.0],
        "displayName": "Cutout D1",
        "compatibleFixtureTypes": ["singleLeftSlot", "trashBinAdapter"]
      },
      {
        "id": "D2",
        "position": [164.0, 0.0, 0.0],
        "displayName": "Cutout D2",
        "compatibleFixtureTypes": ["singleCenterSlot"]
      },
      {
        "id": "D3",
        "position": [328.0, 0.0, 0.0],
        "displayName": "Cutout D3",
        "compatibleFixtureTypes": [
          "singleRightSlot",
          "stagingAreaRightSlot",
          "trashBinAdapter",
          "wasteChuteRightAdapter",
          "wasteChuteRightAdapterWithStagingAreaSlot"
        ]
      },
      {
        "id": "C1",
        "position": [0.0, 107, 0.0],
        "displayName": "Cutout C1",
        "compatibleFixtureTypes": ["singleLeftSlot", "trashBinAdapter"]
      },
      {
        "id": "C2",
        "position": [164.0, 107, 0.0],
        "displayName": "Cutout C2",
        "compatibleFixtureTypes": ["singleCenterSlot"]
      },
      {
        "id": "C3",
        "position": [328.0, 107, 0.0],
        "displayName": "Cutout C3",
        "compatibleFixtureTypes": [
          "singleRightSlot",
          "stagingAreaRightSlot",
          "trashBinAdapter"
        ]
      },
      {
        "id": "B1",
        "position": [0.0, 214.0, 0.0],
        "displayName": "Cutout B1",
        "compatibleFixtureTypes": ["singleLeftSlot", "trashBinAdapter"]
      },
      {
        "id": "B2",
        "position": [164.0, 214.0, 0.0],
        "displayName": "Cutout B2",
        "compatibleFixtureTypes": ["singleCenterSlot"]
      },
      {
        "id": "B3",
        "position": [328.0, 214.0, 0.0],
        "displayName": "Cutout B3",
        "compatibleFixtureTypes": [
          "singleRightSlot",
